import React from 'react';
import Link from 'next/link';
import {
  FileCheck,
  Scale,
  AlertTriangle,
  CreditCard,
  Ban,
  Mail,
  Award
} from 'lucide-react';

export const metadata = {
  title: 'Terms of Service — CSS KRO',
  description: 'Terms and conditions governing your access and usage of the CSS KRO preparation portal.',
};

export default function TermsOfServicePage() {
  const lastUpdated = 'September 12, 2025';

  const sections = [
    {
      id: 'acceptance',
      title: '1. Acceptance of Terms',
      icon: <FileCheck className="w-5 h-5 text-accent-primary" />,
      content: (
        <>
          <p className="mb-3">
            By registering for, accessing, or using the <strong>CSS KRO</strong> portal (the &ldquo;Service&rdquo;), you confirm that you have read, understood, and agreed to be legally bound by these Terms of Service and our Privacy Policy.
          </p>
          <p>
            If you do not agree to all provisions of these Terms, you must immediately discontinue your use of the platform and any associated features.
          </p>
        </>
      ),
    },
    {
      id: 'eligibility-account',
      title: '2. Eligibility & Account Security',
      icon: <Scale className="w-5 h-5 text-accent-gold" />,
      content: (
        <>
          <p className="mb-3">
            You must be at least 16 years of age or possess legal capacity to enter binding agreements in the Islamic Republic of Pakistan or your jurisdiction of residence.
          </p>
          <ul className="list-disc pl-5 space-y-2">
            <li>You agree to provide accurate, truthful, and current information when creating an account.</li>
            <li>You are solely responsible for maintaining the confidentiality of your credentials and all activity occurring under your account.</li>
            <li>You must promptly notify CSS KRO if you suspect any unauthorized access to your profile.</li>
          </ul>
        </>
      ),
    },
    {
      id: 'ai-disclaimer',
      title: '3. AI Evaluation Disclaimer & Academic Guidance',
      icon: <AlertTriangle className="w-5 h-5 text-accent-primary" />,
      content: (
        <>
          <div className="p-4 rounded-xl bg-amber-50 border border-amber-200 mb-3 text-amber-900 text-xs sm:text-sm leading-relaxed">
            <strong>Important Educational Disclaimer:</strong> CSS KRO&apos;s AI Essay Checker is an assistive preparation tool designed to highlight grammar, structural cohesion, and analytical style. It does <em>not</em> represent the Federal Public Service Commission (FPSC), nor does any score guarantee passing marks in the official CSS competitive examination.
          </div>
          <p className="mb-3">
            Civil service examination results depend entirely on the discretion of official FPSC examiners, historical curves, and the candidate&apos;s holistic performance across all compulsory and optional papers.
          </p>
          <p>
            CSS KRO disclaims any liability for examination outcomes, score discrepancies, or decisions made on the basis of feedback generated by our automated tools.
          </p>
        </>
      ),
    },
    {
      id: 'credits-subscriptions',
      title: '4. Evaluation Credits & Subscription Terms',
      icon: <CreditCard className="w-5 h-5 text-accent-gold" />,
      content: (
        <>
          <ul className="list-disc pl-5 space-y-2 mb-3">
            <li>
              <strong>Free Tier Quota:</strong> Every registered user is granted 5 evaluation credits per calendar month at no monetary charge. Credits reset automatically on the 1st of each month and do not accumulate across billing cycles.
            </li>
            <li>
              <strong>Premium Tier:</strong> Upgraded accounts receive 50 essay evaluation credits per month along with priority processing queues and in-depth analytical breakdowns.
            </li>
            <li>
              <strong>Non-Transferability:</strong> Credits are tied exclusively to the registered user account and cannot be sold, gifted, or transferred to other accounts.
            </li>
            <li>
              <strong>Billing &amp; Cancellations:</strong> Paid plans renew automatically unless cancelled prior to the conclusion of the active billing period. You may cancel at any time from your account settings.
            </li>
          </ul>
        </>
      ),
    },
    {
      id: 'acceptable-use',
      title: '5. Acceptable Use & Prohibited Conduct',
      icon: <Ban className="w-5 h-5 text-accent-primary" />,
      content: (
        <>
          <p className="mb-3">When using CSS KRO, you explicitly agree not to:</p>
          <ul className="list-disc pl-5 space-y-2">
            <li>Use automated scrapers, crawlers, or bots to harvest past papers, syllabi, or database materials.</li>
            <li>Attempt to reverse-engineer, decompile, or bypass the authentication or credit-metering mechanisms.</li>
            <li>Submit essays containing unlawful, defamatory, hate speech, or malicious computer code.</li>
            <li>Share login accounts among multiple individuals to circumvent plan limits.</li>
          </ul>
        </>
      ),
    },
    {
      id: 'intellectual-property',
      title: '6. Intellectual Property Rights',
      icon: <Award className="w-5 h-5 text-accent-gold" />,
      content: (
        <>
          <p className="mb-3">
            <strong>Your Content:</strong> You retain complete ownership and copyright of any essays, outlines, or notes you submit to the platform.
          </p>
          <p>
            <strong>Platform Content:</strong> The CSS KRO logo, visual identity, software, layout, curated exam syllabi, and proprietary evaluation algorithms are the exclusive property of CSS KRO and protected under copyright laws of Pakistan and international treaties.
          </p>
        </>
      ),
    },
    {
      id: 'governing-law',
      title: '7. Governing Law & Dispute Resolution',
      icon: <Scale className="w-5 h-5 text-accent-primary" />,
      content: (
        <>
          <p className="mb-3">
            These Terms shall be governed by, and construed in accordance with, the laws of the Islamic Republic of Pakistan, without regard to its conflict of law principles.
          </p>
          <p>
            Any disputes arising from or relating to the Service shall be subject to the exclusive jurisdiction of the competent courts in Islamabad, Pakistan.
          </p>
        </>
      ),
    },
    {
      id: 'contact-terms',
      title: '8. Legal Inquiries & Notice',
      icon: <Mail className="w-5 h-5 text-accent-gold" />,
      content: (
        <>
          <p className="mb-3">
            For questions regarding these Terms or formal legal notices, please write to:
          </p>
          <div className="p-4 rounded-xl bg-white border border-gray-200 text-sm">
            <p className="font-semibold text-text-primary">CSS KRO Legal Affairs</p>
            <p className="text-text-muted mt-1">Email: <a href="mailto:legal@csskro.com" className="text-accent-primary underline">legal@csskro.com</a></p>
            <p className="text-text-muted">Islamabad, Islamic Republic of Pakistan</p>
          </div>
        </>
      ),
    },
  ];

  return (
    <div className="min-h-screen" style={{ background: '#F5F0E8' }}>
      {/* ── HERO ── */}
      <section
        className="relative py-20 pt-32 text-center"
        style={{
          background: '#0B1E3D',
          backgroundImage: `url("data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='%23ffffff' fill-opacity='0.08'%3E%3Cpath d='M36 34v-4h-2v4h-4v2h4v4h2v-4h4v-2h-4zm0-30V0h-2v4h-4v2h4v4h2V6h4V4h-4zM6 34v-4H4v4H0v2h4v4h2v-4h4v-2H6zM6 4V0H4v4H0v2h4v4h2V6h4V4H6z'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E")`,
        }}
      >
        <div className="max-w-4xl mx-auto px-6">
          <p className="font-body text-xs font-semibold tracking-[0.2em] text-accent-gold uppercase mb-4">
            TERMS &amp; CONDITIONS
          </p>
          <h1 className="font-display text-4xl sm:text-5xl lg:text-6xl font-semibold text-white mb-4 leading-tight">
            Terms of Service
          </h1>
          <p className="font-body text-sm text-text-on-dark/70">
            Last Updated: {lastUpdated}
          </p>
        </div>
      </section>

      {/* ── CONTENT ── */}
      <section className="py-16">
        <div className="max-w-4xl mx-auto px-6">
          <div className="mb-10 p-6 rounded-2xl bg-white/70 border border-gray-200">
            <p className="font-body text-sm text-text-muted leading-relaxed">
              Please read these Terms of Service carefully before utilizing our platform, materials, and automated AI essay evaluation services. These terms establish the legal framework under which CSS KRO is made available to you.
            </p>
          </div>

          <div className="space-y-8">
            {sections.map((sec) => (
              <div
                key={sec.id}
                id={sec.id}
                className="p-8 rounded-2xl transition-all duration-200"
                style={{
                  background: 'rgba(255,255,255,0.92)',
                  border: '1px solid rgba(200,150,46,0.20)',
                  boxShadow: '0 4px 20px rgba(26,18,7,0.04)',
                }}
              >
                <div className="flex items-center gap-3 mb-4">
                  <div className="w-10 h-10 rounded-lg flex items-center justify-center bg-gray-50 border border-gray-100">
                    {sec.icon}
                  </div>
                  <h2 className="font-display text-2xl font-semibold text-text-primary">
                    {sec.title}
                  </h2>
                </div>
                <div className="font-body text-sm text-text-muted leading-relaxed">
                  {sec.content}
                </div>
              </div>
            ))}
          </div>

          <div className="mt-12 text-center pt-8 border-t border-gray-300">
            <p className="font-body text-xs text-text-muted mb-4">
              Have questions or need assistance with your subscription terms?
            </p>
            <Link
              href="/contact"
              className="inline-flex items-center gap-2 px-6 py-2.5 rounded-full font-body text-xs font-semibold text-white transition-all hover:scale-105"
              style={{ background: 'linear-gradient(135deg, #E8650A 0%, #C8962E 100%)' }}
            >
              Contact Support
            </Link>
          </div>
        </div>
      </section>
    </div>
  );
}
